config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :rooms do
    resources :viewings
    resources :bookings
  end

  resources :rmcats
  resources :extras
  resources :extracats
  resources :enquiries
  resources :additions

  root :to => redirect('/pages/home')
  get 'pages/home'
  get 'pages/contactus' => 'enquiries#new'
end

app/models/rmcat.rb
# @author Tom Cox <https://github.com/koxzi95>
# @author Richard Mitchell <https://github.com/mr-mitch>
class Rmcat < ActiveRecord::Base

  has_many :rooms

  def rmcat_info
    "#{rmtype}"
  end

  def rmtype=(s)
    super s.titleize
  end

  validates :rmtype, :presence => {:message => "cannot be blank."}

  # before I am destroyed, check if rmcat is deletable
  before_destroy :rmcat_deletable?

  private
  def rmcat_deletable?
    # the rmcat is deletable if it has no rooms assigned to it
    self.rooms.empty?
  end
end

app/controllers/rmcats_controller.rb
# @author Richard Mitchell <https://github.com/mr-mitch>
# @author Tom Cox <https://github.com/koxzi95>
class RmcatsController < ApplicationController
  # @see def resource_not_found
  around_filter :resource_not_found
  before_action :set_rmcat, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @rmcats = Rmcat.all
  end

  def show
  end

  def new
    @rmcat = Rmcat.new
  end

  def edit
  end

  def create
    @rmcat = Rmcat.new(rmcat_params)

    if @rmcat.save
      redirect_to @rmcat, notice: 'Room Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @rmcat.update(rmcat_params)
      redirect_to @rmcat, notice: 'Room Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @rmcat.destroy
    # If the Rmcat has been sucessfully destroyed
    if @rmcat.destroy
      redirect_to rmcats_url, notice: 'Room Category was successfully destroyed.'
    else
      redirect_to rmcats_url, notice: 'Cannot delete assigned Room Category.'
    end
  end

  private

  def set_rmcat
    @rmcat = Rmcat.find(params[:id])
  end

  # If resource not found redirect to root and flash error.
  def resource_not_found
    yield
  rescue ActiveRecord::RecordNotFound
    redirect_to root_url, :notice => "Room Category not found."
  end

  def rmcat_params
    params.require(:rmcat).permit(:rmtype)
  end
end

app/helpers/rmcats_helper.rb
module RmcatsHelper
end

app/views/rmcats/_form.html.erb
<%= form_for @rmcat, :html => {:multipart => true} do |f| %>
    <% if @rmcat.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@rmcat.errors.count, "error") %> prohibited this rmcat from being saved:</h2>
          <ul>
            <% @rmcat.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="main-form">
      <fieldset>
        <div class="field">
          <%= f.label :rmtype, "Room Type:" %><br>
          <%= f.text_field :rmtype %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      </fieldset>
    </div>
<% end %>

app/views/rmcats/edit.html.erb
<div class="main-title"><h1>Editing Room Type</h1></div>
<div class="main-form">
  <%= render 'form' %>
  <%= link_to 'Back', rmcats_path %>
</div>

app/views/rmcats/index.html.erb
<div class="main-form">
  <h1>Listing Room Types</h1>
  <fieldset>
    <table>
      <thead>
      <tr>
        <th>Room Type</th>
        <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>
      <% @rmcats.each do |rmcat| %>
          <tr>
            <td><%= rmcat.rmtype %></td>
            <td><%= link_to 'Edit', edit_rmcat_path(rmcat) %></td>
            <td><%= link_to 'Destroy', rmcat, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    </br>
    <%= link_to 'New Room Category', new_rmcat_path %>
  </fieldset>
  <div>

app/views/rmcats/new.html.erb
<div class="main-title"><h1>New Room Type:</h1></div>
<div class="main-form">
  <%= render 'form' %>
  <%= link_to 'Back', rmcats_path %>
</div>

app/views/rmcats/show.html.erb
<div class="main-form">
  <fieldset>
    <p>
      <strong>Room Type:</strong>
      <%= @rmcat.rmtype %>
    </p>
    <%= link_to 'Edit', edit_rmcat_path(@rmcat) %> |
    <%= link_to 'Back', rmcats_path %>
  </fieldset>
</div>