config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :rooms do
    resources :viewings
    resources :bookings
  end

  resources :rmcats
  resources :extras
  resources :extracats
  resources :enquiries
  resources :additions

  root :to => redirect('/pages/home')
  get 'pages/home'
  get 'pages/contactus' => 'enquiries#new'
end

app/models/extracat.rb
# @author Richard Mitchell <https://github.com/mr-mitch>
# @author Stacey Rees <https://github.com/staceysmells>
class Extracat < ActiveRecord::Base
  has_many :extras

  def extracat_info
    "#{id} #{extratype}"
  end

  def extratype=(s)
    super s.titleize
  end

  validates :extratype, :presence => {:message => "cannot be blank."}

  # before I am destroyed, check if rmcat is deletable
  before_destroy :extracat_deletable?

  private
  def extracat_deletable?
    # the rmcat is deletable if it has no rooms assigned to it
    self.extras.empty?
  end
end

app/controllers/extracats_controller.rb
# @author Stacey Rees <https://github.com/staceysmells>
# @author Richard Mitchell <https://github.com/mr-mitch>
class ExtracatsController < ApplicationController
  # @see def resource_not_found
  around_filter :resource_not_found
  before_action :set_extracat, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @extracats = Extracat.all
  end

  def show
  end

  def new
    @extracat = Extracat.new
  end

  def edit
  end

  def create
    @extracat = Extracat.new(extracat_params)

    if @extracat.save
      redirect_to @extracat, notice: 'Extracat was successfully created.'
    else
      render :new
    end
  end

  def update
    if @extracat.update(extracat_params)
      redirect_to @extracat, notice: 'Extracat was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @extracat.destroy
    if @extracat.destroy
      redirect_to extracats_url, notice: 'Extracat was successfully destroyed.'
    else
      redirect_to extracats_url, notice: 'Cannot delete assigned Extra Category.'
    end
  end

  private

  def set_extracat
    @extracat = Extracat.find(params[:id])
  end

  # If resource not found redirect to root and flash error.
  def resource_not_found
    yield
  rescue ActiveRecord::RecordNotFound
    redirect_to root_url, :notice => "Extra Category not found."
  end

  def extracat_params
    params.require(:extracat).permit(:extratype)
  end
end

app/helpers/extracats_helper.rb
module ExtracatsHelper
end

app/views/extracats/_form.html.erb
<%= form_for(@extracat) do |f| %>
    <% if @extracat.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@extracat.errors.count, "error") %> prohibited this extracat from being saved:</h2>
          <ul>
            <% @extracat.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="main-form">
      <fieldset>
        <div class="field">
          <%= f.label :extratype %><br>
          <%= f.text_field :extratype %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      </fieldset>
    </div>
<% end %>

app/views/extracats/edit.html.erb
<div class="main-title"><h1>Edit Extracat</h1></div>
<div class="main-form">
  <%= render 'form' %>
  <%= link_to 'Back', extracats_path %>
</div>

app/views/extracats/index.html.erb
<div class="main-form">
  <h1>Listing Extracats</h1>
  <fieldset>
    <table>
      <thead>
      <tr>
        <th>Extratype</th>
        <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>
      <% @extracats.each do |extracat| %>
          <tr>
            <td><%= extracat.extratype %></td>
            <td><%= link_to 'Show', extracat %></td>
            <td><%= link_to 'Edit', edit_extracat_path(extracat) %></td>
            <td><%= link_to 'Destroy', extracat, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to 'New Extracat', new_extracat_path %>
  </fieldset>
</div>

app/views/extracats/new.html.erb
<div class="main-title"><h1>New Extra Type</h1></div>
<div class="main-form">
  <%= render 'form' %>
  <%= link_to 'Back', extracats_path %>
</div>

app/views/extracats/show.html.erb
<div class="main-form">
  <fieldset>
    <p>
      <strong>Extratype:</strong>
      <%= @extracat.extratype %>
    </p>
    <%= link_to 'Edit', edit_extracat_path(@extracat) %> |
    <%= link_to 'Back', extracats_path %>
  </fieldset>
</div>