config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :rooms do
    resources :viewings
    resources :bookings
  end

  resources :rmcats
  resources :extras
  resources :extracats
  resources :enquiries
  resources :additions

  root :to => redirect('/pages/home')
  get 'pages/home'
  get 'pages/contactus' => 'enquiries#new'
end

app/models/room.rb
# @author Richard Mitchell <https://github.com/mr-mitch>
class Room < ActiveRecord::Base
  belongs_to :rmcat
  has_many :viewings
  has_many :bookings
  # has_many :extras

  has_attached_file :picture, :styles => {:medium => "300x300>", :thumb => "100x100>"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  validates_attachment_presence :picture

  validates :name, :presence => {:message => "cannot be blank ..."}
  validates :name, :length => {:in => 2..35, :message => "must be between two and thirty five characters"}

  validates :description, :presence => {:message => "cannot be blank ..."}
  validates :description, :length => {:maximum => 2000, :message => "maximum length 2000 characters"}

  validates :size, :presence => {:message => "cannot be blank ..."}
  validates :size, :numericality => {:greater_than_or_equal_to => 10, :message => "Size: cannot be less than ten"}
  validates :size, :numericality => {:less_than => 2001, :message => "Price: cannot more than 2000"}

  validates :capacity, :presence => {:message => "cannot be blank ..."}
  validates :capacity, :numericality => {:greater_than_or_equal_to => 10, :message => "Size: cannot be less than ten"}
  validates :capacity, :numericality => {:less_than => 1001, :message => "Price: cannot more than 1000"}

  validates :price, :presence => {:message => "cannot be blank ..."}
  validates :price, :numericality => {:greater_than_or_equal_to => 100, :message => "Price: cannot be less than 100"}
  validates :price, :numericality => {:less_than => 5001, :message => "Price: cannot more than 5000"}
end

app/controllers/rooms_controller.rb
# @author Tom Cox <https://github.com/koxzi95>
class RoomsController < ApplicationController
  # @see def resource_not_found
  around_filter :resource_not_found
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  # This is the CanCan helper for auth.
  # The skip is so users can view the rooms but nothing else.
  load_and_authorize_resource
  skip_authorize_resource :only => :show

  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Room.new
    #Single auth
    #authorize! :new, @room
  end

  def edit
  end

  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to @room, notice: 'Room was successfully created.'
    else
      render :new
    end
  end

  def update
    if @room.update(room_params)
      redirect_to @room, notice: 'Room was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_url, notice: 'Room was successfully destroyed.'
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  # If resource not found redirect to root and flash error.
  def resource_not_found
    yield
  rescue ActiveRecord::RecordNotFound
    redirect_to root_url, :notice => "Room not found."
  end

  def room_params
    params.require(:room).permit(:name, :description, :size, :capacity, :price, :picture, :rmcat_id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
    <% if @room.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>
          <ul>
            <% @room.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="main-form">
      <fieldset>
        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :rmcat_id, "Room Type:" %><br/>
          <%= f.collection_select :rmcat_id, Rmcat.all, :id, :rmcat_info, {:include_blank => 'Please Select'} %>
        </div>
        <div class="field">
          <%= f.label :description, "Description:" %><br>
          <%= f.text_area :description %>
        </div>
        <div class="field">
          <%= f.label :size, "Size (square feet):" %><br>
          <%= f.text_field :size %>
        </div>
        <div class="field">
          <%= f.label :capacity, "Capacity:" %><br>
          <%= f.number_field :capacity %>
        </div>
        <div class="field">
          <%= f.label :price, "Price:" %><br>
          <%= f.text_field :price %>
        </div>
        <div class="field">
          <%= f.label :picture, "Image:" %><br>
          <%= f.file_field :picture %>
        </div>
        <br>

        <div class="actions">
          <%= f.submit %>
        </div>
      </fieldset>
    </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="main-title">Edit a Room</div>
<div class="main-form">
  <%= render 'form' %>
  <%= link_to 'Back', rooms_path %>
</div>

app/views/rooms/index.html.erb
<nav class="roomnavbar navbar-default" role="navigation">
  <div class="roomcontainer">
    <div class="rooomnavbar-header">
      <ul class="roomliststyle">
        <li><a class="roomnavbar-brand" href="/rooms/1">Maple Room</a></li>
        <li><a class="roomnavbar-brand" href="/rooms/2">Castle Room</a></li>
        <li><a class="roomnavbar-brand" href="/rooms/3">Regal Room</a></li>
        <li><a class="roomnavbar-brand" href="/rooms/4">Grand Hall</a></li>
        <li><a class="roomnavbar-brand" href="/rooms/5">Beaumant</a></li>
        <li><a class="roomnavbar-brand" href="/rooms/6">Belverdere</a></li>
        <li><a class="roomnavbar-brand" href="/rooms/7">Winter Wonderland</a></li>
        <li><a class="roomnavbar-brand" href="/rooms/8">Ambleside</a></li>
        <li><a class="roomnavbar-brand" href="/rooms/9">Lakeside</a></li>
      </ul>
    </div>
  </div>
</nav>
<body>
<div class="landing-image">
  <div id="carousel" class="owl-carousel">
    <div> <%= image_tag("rooms1.jpg") %> </div>
    <div> <%= image_tag("rooms2.jpg") %> </div>
    <div> <%= image_tag("rooms3.jpg") %> </div>
    <div> <%= image_tag("rooms4.jpg") %> </div>
    <div> <%= image_tag("rooms5.jpg") %> </div>
    <div> <%= image_tag("rooms6.jpg") %> </div>
    <div> <%= image_tag("rooms7.jpg") %> </div>
  </div>
</div>
</body>
<script>
    $(document).ready(function () {
        $("#carousel").owlCarousel({
            items: 1, //1 items above 1000px browser width
            autoPlay: true
        });
    });
</script>

app/views/rooms/new.html.erb
<div class="main-title">New Room</div>
<div class="main-form">
  <%= render 'form' %>
  <%= link_to 'Back', rooms_path %>
</div>

app/views/rooms/rooms.html.erb
<div id="all-content">
  <% @rooms.each do |room| %>
      <div id="img-box" , title="select image for more details ...">
        <%= link_to (image_tag room.picture, :size => "100x125"), room %>
      </div>
      <div id="details-box">
        <div id="title-box">
          <%= room.name %>
        </div>
        <div id="rmtype">
          Room Type: <%= room.rmcat.rmtype %>
        </div>
        <div id="size-box">
          Room Size: <%= room.size %> Square Feet
        </div>
        <div id="capacity">
          Capacity: <%= room.capacity %> People
        </div>
        <div id="price-box">
          Price: <%= number_to_currency room.price, unit: "£" %>
        </div>
      </div>
  <% end %>

app/views/rooms/show.html.erb
<nav class="roomnavbar navbar-default" role="navigation">
  <div class="roomcontainer">
    <div class="rooomnavbar-header">
      <!-- <div class="roomheader"><a class="roomnavbar-brand" href="/rooms">Rooms</a></div> -->
      <ul class="roomliststyle">
        <li><a class="roomnavbar-brand" href="/rooms/1">Maple Room</a></li>
        <li><a class="roomnavbar-brand" href="/rooms/2">Castle Room</a></li>
        <li><a class="roomnavbar-brand" href="/rooms/3">Regal Room</a></li>
        <li><a class="roomnavbar-brand" href="/rooms/4">Grand Hall</a></li>
        <li><a class="roomnavbar-brand" href="/rooms/5">Beaumant</a></li>
        <li><a class="roomnavbar-brand" href="/rooms/6">Belverdere</a></li>
        <li><a class="roomnavbar-brand" href="/rooms/7">Winter Wonderland</a></li>
        <li><a class="roomnavbar-brand" href="/rooms/8">Ambleside</a></li>
        <li><a class="roomnavbar-brand" href="/rooms/9">Lakeside</a></li>
      </ul>
    </div>
  </div>
</nav>
<div class="room-title"> <%= @room.name %> </div>
<div id="room-img">
  <%= link_to (image_tag @room.picture, size: "650x500"), rooms_path, :title => 'return to all.' %>
</div>
<div id="room-details">
  <div class="room-show">
    Room Type: <%= @room.rmcat.rmtype %>
  </div>
  <div class="room-show">
    Description: <%= @room.description %>
  </div>
  <div class="room-show">
    Room Size: <%= @room.size %> sqft
  </div>
  <div class="room-show">
    Room Capacity: <%= @room.capacity %> People
  </div>
  <div class="room-show">
    Room Price: <%= number_to_currency @room.price, unit: "£" %>
    <br/>
    <%= link_to 'Back', rooms_path %>
  </div>
</div>