config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :rooms do
    resources :viewings
    resources :bookings
  end

  resources :rmcats
  resources :extras
  resources :extracats
  resources :enquiries
  resources :additions

  root :to => redirect('/pages/home')
  get 'pages/home'
  get 'pages/contactus' => 'enquiries#new'
end

app/models/enquiry.rb
# @author Tom Cox <https://github.com/koxzi95>
class Enquiry < ActiveRecord::Base

  belongs_to :user
  validates :subject, :presence => {:message => "cannot be blank ..."}
  validates :e_description, :presence => {:message => "cannot be blank ..."}

  def user_info
    "#{id} #{customer_name}"
  end

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  # def headers
  # 	{
  # 		:subject => "mvweddings - enquiry",
  # 		:to => "tomcox.media@gmail.com",
  # 		:from => "#{customer_name} <#{email}>"
  # 	}
  # end
end

app/controllers/enquiries_controller.rb
# @author Tom Cox <https://github.com/koxzi95>
class EnquiriesController < ApplicationController
  # @see def resource_not_found
  around_filter :resource_not_found
  before_action :set_enquiry, only: [:show, :edit, :update, :destroy]
  # This is the CanCan helper for auth.
  # The skip is so users can view the rooms but nothing else.
  load_and_authorize_resource

  def index
    @enquiries = Enquiry.all
  end

  def show
  end

  def new
    @enquiry = Enquiry.new
    render 'pages/contactus'
  end

  def edit
  end

  def create
    @enquiry = Enquiry.new(enquiry_params)
    if current_user.customer?
      @enquiry.user_id = current_user.id
    end
    if @enquiry.save
      redirect_to '/pages/contactus', notice: 'Enquiry was successfully sent.'
    else
      render :new
    end
  end

  def update
    if @enquiry.update(enquiry_params)
      redirect_to @enquiry, notice: 'Enquiry was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @enquiry.destroy
    redirect_to enquiries_url, notice: 'Enquiry was successfully destroyed.'
  end

  private

  def set_enquiry
    @enquiry = Enquiry.find(params[:id])
  end

  # If resource not found redirect to root and flash error.
  def resource_not_found
    yield
  rescue ActiveRecord::RecordNotFound
    redirect_to root_url, :notice => "Room not found."
  end

  def enquiry_params
    params.require(:enquiry).permit(:subject, :e_description, :user_id)
  end
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/views/enquiries/_form.html.erb
<%= form_for(enquiry) do |f| %>
    <% if enquiry.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(enquiry.errors.count, "error") %> prohibited this enquiry from being saved:</h2>
          <ul>
            <% enquiry.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :subject, "Subject:" %><br>
      <%= f.text_field :subject, :size => "40" %>
    </div>
    <div class="field">
      <%= f.label :e_description, "Description:" %><br>
      <%= f.text_area :e_description, :cols => "80", :rows => "10" %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/enquiries/edit.html.erb
<div class="main-title"><h1>Editing Enquiry</h1></div>
<div class="main-form">
  <%= render 'form', enquiry: @enquiry %>
  <%= link_to 'Back', enquiries_path %>
</div>

app/views/enquiries/index.html.erb
<div class="main-form">
  <h1>Listing Enquiries</h1>
  <fieldset>
    <!-- TODO Needs styling so table elements are spaced -->
    <table class="e-table">
      <thead>
      <tr>
        <!-- Want name or email instead -->
        <th>Name</th>
        <th>Email</th>
        <th>Subject</th>
        <!--<th>Description</th>-->
        <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>
      <% @enquiries.each do |enquiry| %>
          <tr>
            <td><%= enquiry.user.customer_name %></td>
            <th><%= enquiry.user.email %></th>
            <td><%= enquiry.subject %></td>
            <td><%#= enquiry.e_description %></td>
            <td><%= link_to 'Show', enquiry %></td>
            <td><%= link_to 'Edit', edit_enquiry_path(enquiry) %></td>
            <td><%= link_to 'Destroy', enquiry, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to 'New Enquiry', new_enquiry_path %>
  </fieldset>

app/views/enquiries/new.html.erb
<div class="main-title"><h1>Send us your enquiry:</h1></div>
<div class="main-form">
  <%= render 'form', enquiry: @enquiry %>
  <%= link_to 'Back', enquiries_path %>
</div>

app/views/enquiries/show.html.erb
<div class="main-form">
  <fieldset>
    <p>
      <strong>Subject:</strong>
      <%= @enquiry.subject %>
    </p>

    <p>
      <strong>Customer Name:</strong>
      <%= @enquiry.user.customer_name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @enquiry.user.email %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @enquiry.e_description %>
    </p>

    <%= link_to 'Edit', edit_enquiry_path(@enquiry) %> |
    <%= link_to 'Back', enquiries_path %>
  </fieldset>
</div>